name: "DEV DEPLOY"

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  ASSUME_ROLE_ARN: ${{ secrets.ASSUME_ROLE_ARN }}

jobs:
  terraform:
    uses: ./.github/workflows/terraform_workflow.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::561909996545:role/github-actions-Kassia-Darcie-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "kassiadarcie-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "kassiadarcie-sa-east-1-terraform-lock"